# Generated by Django 5.1.4 on 2025-01-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_materialcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetail',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='quantity_available',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='materialdetail',
            name='target_class',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='authentication.materialdetail')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
