# Generated by Django 5.1.4 on 2025-01-20 06:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_materialdetail_uploaded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetail',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'txt', 'pptx'])]),
        ),
    ]
