# Generated by Django 5.1.4 on 2025-01-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_materialdetail_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the request was approved.', null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the material was distributed to the student.', null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Optional notes or comments about the request.', null=True),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='quantity_requested',
            field=models.IntegerField(default=1, help_text='The quantity of material requested by the student.'),
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the request was rejected.', null=True),
        ),
    ]
