# Generated by Django 5.1.4 on 2025-01-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_materialrequest_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialrequest',
            name='fulfilled_at',
        ),
        migrations.AddField(
            model_name='materialrequest',
            name='delivered_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the material was marked as delivered.', null=True),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='quantity_requested',
            field=models.PositiveIntegerField(default=1, help_text='The quantity of material requested by the student.'),
        ),
        migrations.AlterField(
            model_name='materialrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='memberdetail',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('admin', 'Admin')], max_length=10),
        ),
    ]
