# Generated by Django 5.1.4 on 2025-01-26 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_remove_materialrequest_fulfilled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialdetail',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
