# Generated by Django 5.1.4 on 2025-01-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_memberdetail_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberdetail',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10),
        ),
        migrations.AlterModelTable(
            name='memberdetail',
            table='authentication_memberdetail',
        ),
    ]
