# Generated by Django 5.1.4 on 2025-02-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_memberdetail_role_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialrequest',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
    ]
